name: tough-love-massage
region: nyc

services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    
    build_command: pip install -r requirements.txt
    run_command: gunicorn --bind 0.0.0.0:8080 --reuse-port --workers 4 main:app
    
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    
    routes:
      - path: /
    
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
      
      - key: PGHOST
        value: ${db.HOSTNAME}
        scope: RUN_TIME
      
      - key: PGPORT
        value: ${db.PORT}
        scope: RUN_TIME
      
      - key: PGDATABASE
        value: ${db.DATABASE}
        scope: RUN_TIME
      
      - key: PGUSER
        value: ${db.USERNAME}
        scope: RUN_TIME
      
      - key: PGPASSWORD
        value: ${db.PASSWORD}
        scope: RUN_TIME
        type: SECRET
      
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
      
      - key: SMTP_SERVER
        scope: RUN_TIME
        type: SECRET
      
      - key: SMTP_PORT
        value: "587"
        scope: RUN_TIME
      
      - key: SMTP_USERNAME
        scope: RUN_TIME
        type: SECRET
      
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      
      - key: ADMIN_EMAIL
        scope: RUN_TIME
        type: SECRET
      
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
      
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET

databases:
  - name: db
    engine: PG
    production: true
    cluster_name: tough-love-massage-db
